package com.hardbug.bibliotecatenango.Models;

import java.sql.Date;

public class Reporte {
    public int Masculinos60 = 0;
    public int Masculinos3059 = 0;
    public int Masculinos1829 = 0;
    public int Masculinos1317 = 0;
    public int Masculinos012 = 0;
    public int MasculinosDis60 = 0;
    public int MasculinosDis3059 = 0;
    public int MasculinosDis1829 = 0;
    public int MasculinosDis1317 = 0;
    public int MasculinosDis012 = 0;
    public int MasculinosTotales = 0;
    public int MasculinosDiscTotales = 0;
    public int FEM60 = 0;
    public int FEM3059 = 0;
    public int FEM1829 = 0;
    public int FEM1317 = 0;
    public int FEM012 = 0;
    public int FEMDis60 = 0;
    public int FEMDis3059 = 0;
    public int FEMDis1829 = 0;
    public int FEMDis1317 = 0;
    public int FEMDis012 = 0;
    public int FEMTotales = 0;
    public int FEMDiscTotales = 0;
    public int TotalUsers = 0;
    public int Preescolar = 0;
    public int Primaria = 0;
    public int Secundaria = 0;
    public int Preparatoria = 0;
    public int Universidad = 0;
    public int Posgrado = 0;
    public int Hogar = 0;
    public int Estudiante = 0;
    public int Empleado = 0;
    public int Desempleado = 0;
    public int ColeccionGeneral = 0;
    public int ColeccionConsulta = 0;
    public int ColeccionInfantil = 0;
    public int PublicacionesPeriodicas = 0;
    public int AudioVisual = 0;
    public int Ludoteca = 0;
    public int Braille = 0;
    public int ColeccionEstatal = 0;
    public int ColeccionEspecial = 0;
    public int ColeccionOtra = 0;
    public int CredencialesExpedidas = 0;
    public int LibrosDomicilio = 0;
    public int ActividadLectura60 = 0;
    public int ActividadLectura3059 = 0;
    public int ActividadLectura1829 = 0;
    public int ActividadLectura1317 = 0;
    public int ActividadLectura012 = 0;
    public int ActividadLecturaTotal = 0;
    public Date FechaInicio = null;
    public Date FechaFin = null;
}
